# Generated by Django 4.1.6 on 2023-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('username', models.CharField(default='user', max_length=100, null=True)),
                ('id', models.PositiveIntegerField(default='', primary_key=True, serialize=False)),
            ],
        ),
    ]
